version: '2.2'
services:
  frontend:
    build:
      context: .
      dockerfile: ./docker_config/votings_frontend/Dockerfile
    restart: on-failure
    volumes:
    - ./votings_frontend/dist:/frontend

  backend:
    build:
      context: .
      dockerfile: ./docker_config/votings_backend/Dockerfile
    volumes:
      - ./votings_backend/db.sqlite3:/backend/db.sqlite3
    restart: on-failure
    mem_limit: 128m

  nginx:
    image: nginx:1.13.7-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default:/etc/nginx/sites-enabled/default
      - ./votings_frontend/dist:/frontend:ro
    depends_on:
      - backend
      - frontend
    restart: on-failure
    mem_limit: 128m

